[tox]
envlist = py{312,313,314}-django{52}

[testenv]
commands = coverage run --parallel -m pytest {posargs}
deps =
    -r{toxinidir}/requirements.txt
    django52: django>=5.2,<5.3

[testenv:lint]
basepython = python3.14
deps =
    -r{toxinidir}/requirements.txt
commands =
    flake8 stores sandbox tests setup.py
    isort -c -q --diff stores tests setup.py

[testenv:coverage-report]
basepython = python3.14
deps = coverage
skip_install = true
commands =
    coverage combine
    coverage report
