# Generated by Django 5.2.17 on 2026-09-26 16:21

import oscar.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_auto_20190812_0459"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeaddress",
            name="code",
            field=oscar.models.fields.NullCharField(
                max_length=255, unique=True, verbose_name="Code"
            ),
        ),
    ]
